POST http://localhost:8080/events
Content-Type: application/json

{
	"name": "Test event",
	"description": "This is a test event",
	"location": "Location of test",
	"dateTime": "2026-01-01T00:00:00.000Z"
}