PUT http://localhost:8080/events/6
Content-Type: application/json
authorization: # Enter JWT here

{
	"name": "Updated event",
	"description": "This is an updated test event",
	"location": "Location of updated test",
	"dateTime": "2026-01-01T00:00:00.000Z"
}