PUT http://localhost:8080/events/6
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzcwODU0NzMwLCJ1c2VySWQiOjJ9.4Z1PKsvu5o1JIKR3z8C8WS7ZO-snTrwjJvybsRipkK8

{
	"name": "Updated event",
	"description": "This is an updated test event",
	"location": "Location of updated test",
	"dateTime": "2026-01-01T00:00:00.000Z"
}